services:
  postgres:
      image: postgres:latest
      ports:
          - 5432:5432
      environment:
          - POSTGRES_USER=root
          - POSTGRES_PASSWORD=password
          - POSTGRES_DB=test
      volumes:
          - ./.data/.postgres:/var/lib/postgresql/data
